// Shared episode catalog: website cards, uploader, playback and search.
window.MH_ANIME_SHOWS = [
  {
    "slug": "death-note",
    "title": "Death Note",
    "episodeCount": 37,
    "episodes": [
      {
        "episode": 1,
        "title": "Rebirth",
        "mediaId": "e01",
        "watchUrl": "watch.html?anime=death-note&episode=1",
        "r2Key": "anime/death-note/e01.mp4",
        "videoPath": "/video/anime/death-note/e01",
        "downloadPath": "/download/anime/death-note/e01"
      },
      {
        "episode": 2,
        "title": "Confrontation",
        "mediaId": "e02",
        "watchUrl": "watch.html?anime=death-note&episode=2",
        "r2Key": "anime/death-note/e02.mp4",
        "videoPath": "/video/anime/death-note/e02",
        "downloadPath": "/download/anime/death-note/e02"
      },
      {
        "episode": 3,
        "title": "Dealings",
        "mediaId": "e03",
        "watchUrl": "watch.html?anime=death-note&episode=3",
        "r2Key": "anime/death-note/e03.mp4",
        "videoPath": "/video/anime/death-note/e03",
        "downloadPath": "/download/anime/death-note/e03"
      },
      {
        "episode": 4,
        "title": "Pursuit",
        "mediaId": "e04",
        "watchUrl": "watch.html?anime=death-note&episode=4",
        "r2Key": "anime/death-note/e04.mp4",
        "videoPath": "/video/anime/death-note/e04",
        "downloadPath": "/download/anime/death-note/e04"
      },
      {
        "episode": 5,
        "title": "Tactics",
        "mediaId": "e05",
        "watchUrl": "watch.html?anime=death-note&episode=5",
        "r2Key": "anime/death-note/e05.mp4",
        "videoPath": "/video/anime/death-note/e05",
        "downloadPath": "/download/anime/death-note/e05"
      },
      {
        "episode": 6,
        "title": "Unraveling",
        "mediaId": "e06",
        "watchUrl": "watch.html?anime=death-note&episode=6",
        "r2Key": "anime/death-note/e06.mp4",
        "videoPath": "/video/anime/death-note/e06",
        "downloadPath": "/download/anime/death-note/e06"
      },
      {
        "episode": 7,
        "title": "Overcast",
        "mediaId": "e07",
        "watchUrl": "watch.html?anime=death-note&episode=7",
        "r2Key": "anime/death-note/e07.mp4",
        "videoPath": "/video/anime/death-note/e07",
        "downloadPath": "/download/anime/death-note/e07"
      },
      {
        "episode": 8,
        "title": "Glare",
        "mediaId": "e08",
        "watchUrl": "watch.html?anime=death-note&episode=8",
        "r2Key": "anime/death-note/e08.mp4",
        "videoPath": "/video/anime/death-note/e08",
        "downloadPath": "/download/anime/death-note/e08"
      },
      {
        "episode": 9,
        "title": "Encounter",
        "mediaId": "e09",
        "watchUrl": "watch.html?anime=death-note&episode=9",
        "r2Key": "anime/death-note/e09.mp4",
        "videoPath": "/video/anime/death-note/e09",
        "downloadPath": "/download/anime/death-note/e09"
      },
      {
        "episode": 10,
        "title": "Doubt",
        "mediaId": "e10",
        "watchUrl": "watch.html?anime=death-note&episode=10",
        "r2Key": "anime/death-note/e10.mp4",
        "videoPath": "/video/anime/death-note/e10",
        "downloadPath": "/download/anime/death-note/e10"
      },
      {
        "episode": 11,
        "title": "Assault",
        "mediaId": "e11",
        "watchUrl": "watch.html?anime=death-note&episode=11",
        "r2Key": "anime/death-note/e11.mp4",
        "videoPath": "/video/anime/death-note/e11",
        "downloadPath": "/download/anime/death-note/e11"
      },
      {
        "episode": 12,
        "title": "Love",
        "mediaId": "e12",
        "watchUrl": "watch.html?anime=death-note&episode=12",
        "r2Key": "anime/death-note/e12.mp4",
        "videoPath": "/video/anime/death-note/e12",
        "downloadPath": "/download/anime/death-note/e12"
      },
      {
        "episode": 13,
        "title": "Confession",
        "mediaId": "e13",
        "watchUrl": "watch.html?anime=death-note&episode=13",
        "r2Key": "anime/death-note/e13.mp4",
        "videoPath": "/video/anime/death-note/e13",
        "downloadPath": "/download/anime/death-note/e13"
      },
      {
        "episode": 14,
        "title": "Friend",
        "mediaId": "e14",
        "watchUrl": "watch.html?anime=death-note&episode=14",
        "r2Key": "anime/death-note/e14.mp4",
        "videoPath": "/video/anime/death-note/e14",
        "downloadPath": "/download/anime/death-note/e14"
      },
      {
        "episode": 15,
        "title": "Wager",
        "mediaId": "e15",
        "watchUrl": "watch.html?anime=death-note&episode=15",
        "r2Key": "anime/death-note/e15.mp4",
        "videoPath": "/video/anime/death-note/e15",
        "downloadPath": "/download/anime/death-note/e15"
      },
      {
        "episode": 16,
        "title": "Decision",
        "mediaId": "e16",
        "watchUrl": "watch.html?anime=death-note&episode=16",
        "r2Key": "anime/death-note/e16.mp4",
        "videoPath": "/video/anime/death-note/e16",
        "downloadPath": "/download/anime/death-note/e16"
      },
      {
        "episode": 17,
        "title": "Execution",
        "mediaId": "e17",
        "watchUrl": "watch.html?anime=death-note&episode=17",
        "r2Key": "anime/death-note/e17.mp4",
        "videoPath": "/video/anime/death-note/e17",
        "downloadPath": "/download/anime/death-note/e17"
      },
      {
        "episode": 18,
        "title": "Ally",
        "mediaId": "e18",
        "watchUrl": "watch.html?anime=death-note&episode=18",
        "r2Key": "anime/death-note/e18.mp4",
        "videoPath": "/video/anime/death-note/e18",
        "downloadPath": "/download/anime/death-note/e18"
      },
      {
        "episode": 19,
        "title": "Matsuda",
        "mediaId": "e19",
        "watchUrl": "watch.html?anime=death-note&episode=19",
        "r2Key": "anime/death-note/e19.mp4",
        "videoPath": "/video/anime/death-note/e19",
        "downloadPath": "/download/anime/death-note/e19"
      },
      {
        "episode": 20,
        "title": "Makeshift",
        "mediaId": "e20",
        "watchUrl": "watch.html?anime=death-note&episode=20",
        "r2Key": "anime/death-note/e20.mp4",
        "videoPath": "/video/anime/death-note/e20",
        "downloadPath": "/download/anime/death-note/e20"
      },
      {
        "episode": 21,
        "title": "Performance",
        "mediaId": "e21",
        "watchUrl": "watch.html?anime=death-note&episode=21",
        "r2Key": "anime/death-note/e21.mp4",
        "videoPath": "/video/anime/death-note/e21",
        "downloadPath": "/download/anime/death-note/e21"
      },
      {
        "episode": 22,
        "title": "Guidance",
        "mediaId": "e22",
        "watchUrl": "watch.html?anime=death-note&episode=22",
        "r2Key": "anime/death-note/e22.mp4",
        "videoPath": "/video/anime/death-note/e22",
        "downloadPath": "/download/anime/death-note/e22"
      },
      {
        "episode": 23,
        "title": "Frenzy",
        "mediaId": "e23",
        "watchUrl": "watch.html?anime=death-note&episode=23",
        "r2Key": "anime/death-note/e23.mp4",
        "videoPath": "/video/anime/death-note/e23",
        "downloadPath": "/download/anime/death-note/e23"
      },
      {
        "episode": 24,
        "title": "Revival",
        "mediaId": "e24",
        "watchUrl": "watch.html?anime=death-note&episode=24",
        "r2Key": "anime/death-note/e24.mp4",
        "videoPath": "/video/anime/death-note/e24",
        "downloadPath": "/download/anime/death-note/e24"
      },
      {
        "episode": 25,
        "title": "Silence",
        "mediaId": "e25",
        "watchUrl": "watch.html?anime=death-note&episode=25",
        "r2Key": "anime/death-note/e25.mp4",
        "videoPath": "/video/anime/death-note/e25",
        "downloadPath": "/download/anime/death-note/e25"
      },
      {
        "episode": 26,
        "title": "Renewal",
        "mediaId": "e26",
        "watchUrl": "watch.html?anime=death-note&episode=26",
        "r2Key": "anime/death-note/e26.mp4",
        "videoPath": "/video/anime/death-note/e26",
        "downloadPath": "/download/anime/death-note/e26"
      },
      {
        "episode": 27,
        "title": "Abduction",
        "mediaId": "e27",
        "watchUrl": "watch.html?anime=death-note&episode=27",
        "r2Key": "anime/death-note/e27.mp4",
        "videoPath": "/video/anime/death-note/e27",
        "downloadPath": "/download/anime/death-note/e27"
      },
      {
        "episode": 28,
        "title": "Impatience",
        "mediaId": "e28",
        "watchUrl": "watch.html?anime=death-note&episode=28",
        "r2Key": "anime/death-note/e28.mp4",
        "videoPath": "/video/anime/death-note/e28",
        "downloadPath": "/download/anime/death-note/e28"
      },
      {
        "episode": 29,
        "title": "Father",
        "mediaId": "e29",
        "watchUrl": "watch.html?anime=death-note&episode=29",
        "r2Key": "anime/death-note/e29.mp4",
        "videoPath": "/video/anime/death-note/e29",
        "downloadPath": "/download/anime/death-note/e29"
      },
      {
        "episode": 30,
        "title": "Justice",
        "mediaId": "e30",
        "watchUrl": "watch.html?anime=death-note&episode=30",
        "r2Key": "anime/death-note/e30.mp4",
        "videoPath": "/video/anime/death-note/e30",
        "downloadPath": "/download/anime/death-note/e30"
      },
      {
        "episode": 31,
        "title": "Transfer",
        "mediaId": "e31",
        "watchUrl": "watch.html?anime=death-note&episode=31",
        "r2Key": "anime/death-note/e31.mp4",
        "videoPath": "/video/anime/death-note/e31",
        "downloadPath": "/download/anime/death-note/e31"
      },
      {
        "episode": 32,
        "title": "Selection",
        "mediaId": "e32",
        "watchUrl": "watch.html?anime=death-note&episode=32",
        "r2Key": "anime/death-note/e32.mp4",
        "videoPath": "/video/anime/death-note/e32",
        "downloadPath": "/download/anime/death-note/e32"
      },
      {
        "episode": 33,
        "title": "Scorn",
        "mediaId": "e33",
        "watchUrl": "watch.html?anime=death-note&episode=33",
        "r2Key": "anime/death-note/e33.mp4",
        "videoPath": "/video/anime/death-note/e33",
        "downloadPath": "/download/anime/death-note/e33"
      },
      {
        "episode": 34,
        "title": "Vigilance",
        "mediaId": "e34",
        "watchUrl": "watch.html?anime=death-note&episode=34",
        "r2Key": "anime/death-note/e34.mp4",
        "videoPath": "/video/anime/death-note/e34",
        "downloadPath": "/download/anime/death-note/e34"
      },
      {
        "episode": 35,
        "title": "Malice",
        "mediaId": "e35",
        "watchUrl": "watch.html?anime=death-note&episode=35",
        "r2Key": "anime/death-note/e35.mp4",
        "videoPath": "/video/anime/death-note/e35",
        "downloadPath": "/download/anime/death-note/e35"
      },
      {
        "episode": 36,
        "title": "1.28",
        "mediaId": "e36",
        "watchUrl": "watch.html?anime=death-note&episode=36",
        "r2Key": "anime/death-note/e36.mp4",
        "videoPath": "/video/anime/death-note/e36",
        "downloadPath": "/download/anime/death-note/e36"
      },
      {
        "episode": 37,
        "title": "New World",
        "mediaId": "e37",
        "watchUrl": "watch.html?anime=death-note&episode=37",
        "r2Key": "anime/death-note/e37.mp4",
        "videoPath": "/video/anime/death-note/e37",
        "downloadPath": "/download/anime/death-note/e37"
      }
    ],
    "abbreviation": "DN",
    "page": "death-note.html"
  },
  {
    "slug": "attack-on-titan",
    "title": "Attack on Titan",
    "abbreviation": "AOT",
    "page": "attack-on-titan.html",
    "episodeCount": 94,
    "specialCount": 2,
    "oadCount": 8,
    "numberingNote": "Episodes 88–94 are the episodic cut of the two Final Chapters specials. Specials and OADs have separate routes; do not upload a full special as episode 88.",
    "sources": [
      "https://en.wikipedia.org/wiki/Attack_on_Titan_season_1",
      "https://en.wikipedia.org/wiki/Attack_on_Titan_season_2",
      "https://en.wikipedia.org/wiki/Attack_on_Titan_season_3",
      "https://en.wikipedia.org/wiki/Attack_on_Titan_season_4",
      "https://shingeki.tv/news/archives/8042",
      "https://www.crunchyroll.com/news/latest/2022/5/2/crunchyroll-to-launch-attack-on-titan-oad-english-dub-starting-may-8",
      "https://aot-portal.com/en/animation/oad-archive/"
    ],
    "episodes": [
      {
        "episode": 1,
        "title": "To You, in 2000 Years",
        "animeSeason": 1,
        "seasonEpisode": 1,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E01 · Episode 1",
        "mediaId": "e01",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=1",
        "r2Key": "anime/attack-on-titan/e01.mp4",
        "videoPath": "/video/anime/attack-on-titan/e01",
        "downloadPath": "/download/anime/attack-on-titan/e01"
      },
      {
        "episode": 2,
        "title": "That Day",
        "animeSeason": 1,
        "seasonEpisode": 2,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E02 · Episode 2",
        "mediaId": "e02",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=2",
        "r2Key": "anime/attack-on-titan/e02.mp4",
        "videoPath": "/video/anime/attack-on-titan/e02",
        "downloadPath": "/download/anime/attack-on-titan/e02"
      },
      {
        "episode": 3,
        "title": "A Dim Light Amid Despair",
        "animeSeason": 1,
        "seasonEpisode": 3,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E03 · Episode 3",
        "mediaId": "e03",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=3",
        "r2Key": "anime/attack-on-titan/e03.mp4",
        "videoPath": "/video/anime/attack-on-titan/e03",
        "downloadPath": "/download/anime/attack-on-titan/e03"
      },
      {
        "episode": 4,
        "title": "The Night of the Closing Ceremony",
        "animeSeason": 1,
        "seasonEpisode": 4,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E04 · Episode 4",
        "mediaId": "e04",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=4",
        "r2Key": "anime/attack-on-titan/e04.mp4",
        "videoPath": "/video/anime/attack-on-titan/e04",
        "downloadPath": "/download/anime/attack-on-titan/e04"
      },
      {
        "episode": 5,
        "title": "First Battle",
        "animeSeason": 1,
        "seasonEpisode": 5,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E05 · Episode 5",
        "mediaId": "e05",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=5",
        "r2Key": "anime/attack-on-titan/e05.mp4",
        "videoPath": "/video/anime/attack-on-titan/e05",
        "downloadPath": "/download/anime/attack-on-titan/e05"
      },
      {
        "episode": 6,
        "title": "The World the Girl Saw",
        "animeSeason": 1,
        "seasonEpisode": 6,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E06 · Episode 6",
        "mediaId": "e06",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=6",
        "r2Key": "anime/attack-on-titan/e06.mp4",
        "videoPath": "/video/anime/attack-on-titan/e06",
        "downloadPath": "/download/anime/attack-on-titan/e06"
      },
      {
        "episode": 7,
        "title": "Small Blade",
        "animeSeason": 1,
        "seasonEpisode": 7,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E07 · Episode 7",
        "mediaId": "e07",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=7",
        "r2Key": "anime/attack-on-titan/e07.mp4",
        "videoPath": "/video/anime/attack-on-titan/e07",
        "downloadPath": "/download/anime/attack-on-titan/e07"
      },
      {
        "episode": 8,
        "title": "I Can Hear His Heartbeat",
        "animeSeason": 1,
        "seasonEpisode": 8,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E08 · Episode 8",
        "mediaId": "e08",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=8",
        "r2Key": "anime/attack-on-titan/e08.mp4",
        "videoPath": "/video/anime/attack-on-titan/e08",
        "downloadPath": "/download/anime/attack-on-titan/e08"
      },
      {
        "episode": 9,
        "title": "Whereabouts of His Left Arm",
        "animeSeason": 1,
        "seasonEpisode": 9,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E09 · Episode 9",
        "mediaId": "e09",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=9",
        "r2Key": "anime/attack-on-titan/e09.mp4",
        "videoPath": "/video/anime/attack-on-titan/e09",
        "downloadPath": "/download/anime/attack-on-titan/e09"
      },
      {
        "episode": 10,
        "title": "Response",
        "animeSeason": 1,
        "seasonEpisode": 10,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E10 · Episode 10",
        "mediaId": "e10",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=10",
        "r2Key": "anime/attack-on-titan/e10.mp4",
        "videoPath": "/video/anime/attack-on-titan/e10",
        "downloadPath": "/download/anime/attack-on-titan/e10"
      },
      {
        "episode": 11,
        "title": "Idol",
        "animeSeason": 1,
        "seasonEpisode": 11,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E11 · Episode 11",
        "mediaId": "e11",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=11",
        "r2Key": "anime/attack-on-titan/e11.mp4",
        "videoPath": "/video/anime/attack-on-titan/e11",
        "downloadPath": "/download/anime/attack-on-titan/e11"
      },
      {
        "episode": 12,
        "title": "Wound",
        "animeSeason": 1,
        "seasonEpisode": 12,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E12 · Episode 12",
        "mediaId": "e12",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=12",
        "r2Key": "anime/attack-on-titan/e12.mp4",
        "videoPath": "/video/anime/attack-on-titan/e12",
        "downloadPath": "/download/anime/attack-on-titan/e12"
      },
      {
        "episode": 13,
        "title": "Primal Desire",
        "animeSeason": 1,
        "seasonEpisode": 13,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E13 · Episode 13",
        "mediaId": "e13",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=13",
        "r2Key": "anime/attack-on-titan/e13.mp4",
        "videoPath": "/video/anime/attack-on-titan/e13",
        "downloadPath": "/download/anime/attack-on-titan/e13"
      },
      {
        "episode": 14,
        "title": "Can't Look into His Eyes Yet",
        "animeSeason": 1,
        "seasonEpisode": 14,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E14 · Episode 14",
        "mediaId": "e14",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=14",
        "r2Key": "anime/attack-on-titan/e14.mp4",
        "videoPath": "/video/anime/attack-on-titan/e14",
        "downloadPath": "/download/anime/attack-on-titan/e14"
      },
      {
        "episode": 15,
        "title": "Special Operations Squad",
        "animeSeason": 1,
        "seasonEpisode": 15,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E15 · Episode 15",
        "mediaId": "e15",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=15",
        "r2Key": "anime/attack-on-titan/e15.mp4",
        "videoPath": "/video/anime/attack-on-titan/e15",
        "downloadPath": "/download/anime/attack-on-titan/e15"
      },
      {
        "episode": 16,
        "title": "What Needs to Be Done Now",
        "animeSeason": 1,
        "seasonEpisode": 16,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E16 · Episode 16",
        "mediaId": "e16",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=16",
        "r2Key": "anime/attack-on-titan/e16.mp4",
        "videoPath": "/video/anime/attack-on-titan/e16",
        "downloadPath": "/download/anime/attack-on-titan/e16"
      },
      {
        "episode": 17,
        "title": "Female Titan",
        "animeSeason": 1,
        "seasonEpisode": 17,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E17 · Episode 17",
        "mediaId": "e17",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=17",
        "r2Key": "anime/attack-on-titan/e17.mp4",
        "videoPath": "/video/anime/attack-on-titan/e17",
        "downloadPath": "/download/anime/attack-on-titan/e17"
      },
      {
        "episode": 18,
        "title": "Forest of Giant Trees",
        "animeSeason": 1,
        "seasonEpisode": 18,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E18 · Episode 18",
        "mediaId": "e18",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=18",
        "r2Key": "anime/attack-on-titan/e18.mp4",
        "videoPath": "/video/anime/attack-on-titan/e18",
        "downloadPath": "/download/anime/attack-on-titan/e18"
      },
      {
        "episode": 19,
        "title": "Bite",
        "animeSeason": 1,
        "seasonEpisode": 19,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E19 · Episode 19",
        "mediaId": "e19",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=19",
        "r2Key": "anime/attack-on-titan/e19.mp4",
        "videoPath": "/video/anime/attack-on-titan/e19",
        "downloadPath": "/download/anime/attack-on-titan/e19"
      },
      {
        "episode": 20,
        "title": "Erwin Smith",
        "animeSeason": 1,
        "seasonEpisode": 20,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E20 · Episode 20",
        "mediaId": "e20",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=20",
        "r2Key": "anime/attack-on-titan/e20.mp4",
        "videoPath": "/video/anime/attack-on-titan/e20",
        "downloadPath": "/download/anime/attack-on-titan/e20"
      },
      {
        "episode": 21,
        "title": "Crushing Blow",
        "animeSeason": 1,
        "seasonEpisode": 21,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E21 · Episode 21",
        "mediaId": "e21",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=21",
        "r2Key": "anime/attack-on-titan/e21.mp4",
        "videoPath": "/video/anime/attack-on-titan/e21",
        "downloadPath": "/download/anime/attack-on-titan/e21"
      },
      {
        "episode": 22,
        "title": "The Defeated",
        "animeSeason": 1,
        "seasonEpisode": 22,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E22 · Episode 22",
        "mediaId": "e22",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=22",
        "r2Key": "anime/attack-on-titan/e22.mp4",
        "videoPath": "/video/anime/attack-on-titan/e22",
        "downloadPath": "/download/anime/attack-on-titan/e22"
      },
      {
        "episode": 23,
        "title": "Smile",
        "animeSeason": 1,
        "seasonEpisode": 23,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E23 · Episode 23",
        "mediaId": "e23",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=23",
        "r2Key": "anime/attack-on-titan/e23.mp4",
        "videoPath": "/video/anime/attack-on-titan/e23",
        "downloadPath": "/download/anime/attack-on-titan/e23"
      },
      {
        "episode": 24,
        "title": "Mercy",
        "animeSeason": 1,
        "seasonEpisode": 24,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E24 · Episode 24",
        "mediaId": "e24",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=24",
        "r2Key": "anime/attack-on-titan/e24.mp4",
        "videoPath": "/video/anime/attack-on-titan/e24",
        "downloadPath": "/download/anime/attack-on-titan/e24"
      },
      {
        "episode": 25,
        "title": "Wall",
        "animeSeason": 1,
        "seasonEpisode": 25,
        "group": "main",
        "section": "Season 1",
        "label": "S01 E25 · Episode 25",
        "mediaId": "e25",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=25",
        "r2Key": "anime/attack-on-titan/e25.mp4",
        "videoPath": "/video/anime/attack-on-titan/e25",
        "downloadPath": "/download/anime/attack-on-titan/e25"
      },
      {
        "episode": 26,
        "title": "Beast Titan",
        "animeSeason": 2,
        "seasonEpisode": 1,
        "group": "main",
        "section": "Season 2",
        "label": "S02 E01 · Episode 26",
        "mediaId": "e26",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=26",
        "r2Key": "anime/attack-on-titan/e26.mp4",
        "videoPath": "/video/anime/attack-on-titan/e26",
        "downloadPath": "/download/anime/attack-on-titan/e26"
      },
      {
        "episode": 27,
        "title": "I'm Home",
        "animeSeason": 2,
        "seasonEpisode": 2,
        "group": "main",
        "section": "Season 2",
        "label": "S02 E02 · Episode 27",
        "mediaId": "e27",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=27",
        "r2Key": "anime/attack-on-titan/e27.mp4",
        "videoPath": "/video/anime/attack-on-titan/e27",
        "downloadPath": "/download/anime/attack-on-titan/e27"
      },
      {
        "episode": 28,
        "title": "Southwestward",
        "animeSeason": 2,
        "seasonEpisode": 3,
        "group": "main",
        "section": "Season 2",
        "label": "S02 E03 · Episode 28",
        "mediaId": "e28",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=28",
        "r2Key": "anime/attack-on-titan/e28.mp4",
        "videoPath": "/video/anime/attack-on-titan/e28",
        "downloadPath": "/download/anime/attack-on-titan/e28"
      },
      {
        "episode": 29,
        "title": "Soldier",
        "animeSeason": 2,
        "seasonEpisode": 4,
        "group": "main",
        "section": "Season 2",
        "label": "S02 E04 · Episode 29",
        "mediaId": "e29",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=29",
        "r2Key": "anime/attack-on-titan/e29.mp4",
        "videoPath": "/video/anime/attack-on-titan/e29",
        "downloadPath": "/download/anime/attack-on-titan/e29"
      },
      {
        "episode": 30,
        "title": "Historia",
        "animeSeason": 2,
        "seasonEpisode": 5,
        "group": "main",
        "section": "Season 2",
        "label": "S02 E05 · Episode 30",
        "mediaId": "e30",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=30",
        "r2Key": "anime/attack-on-titan/e30.mp4",
        "videoPath": "/video/anime/attack-on-titan/e30",
        "downloadPath": "/download/anime/attack-on-titan/e30"
      },
      {
        "episode": 31,
        "title": "Warrior",
        "animeSeason": 2,
        "seasonEpisode": 6,
        "group": "main",
        "section": "Season 2",
        "label": "S02 E06 · Episode 31",
        "mediaId": "e31",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=31",
        "r2Key": "anime/attack-on-titan/e31.mp4",
        "videoPath": "/video/anime/attack-on-titan/e31",
        "downloadPath": "/download/anime/attack-on-titan/e31"
      },
      {
        "episode": 32,
        "title": "Close Combat",
        "animeSeason": 2,
        "seasonEpisode": 7,
        "group": "main",
        "section": "Season 2",
        "label": "S02 E07 · Episode 32",
        "mediaId": "e32",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=32",
        "r2Key": "anime/attack-on-titan/e32.mp4",
        "videoPath": "/video/anime/attack-on-titan/e32",
        "downloadPath": "/download/anime/attack-on-titan/e32"
      },
      {
        "episode": 33,
        "title": "The Hunters",
        "animeSeason": 2,
        "seasonEpisode": 8,
        "group": "main",
        "section": "Season 2",
        "label": "S02 E08 · Episode 33",
        "mediaId": "e33",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=33",
        "r2Key": "anime/attack-on-titan/e33.mp4",
        "videoPath": "/video/anime/attack-on-titan/e33",
        "downloadPath": "/download/anime/attack-on-titan/e33"
      },
      {
        "episode": 34,
        "title": "Opening",
        "animeSeason": 2,
        "seasonEpisode": 9,
        "group": "main",
        "section": "Season 2",
        "label": "S02 E09 · Episode 34",
        "mediaId": "e34",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=34",
        "r2Key": "anime/attack-on-titan/e34.mp4",
        "videoPath": "/video/anime/attack-on-titan/e34",
        "downloadPath": "/download/anime/attack-on-titan/e34"
      },
      {
        "episode": 35,
        "title": "Children",
        "animeSeason": 2,
        "seasonEpisode": 10,
        "group": "main",
        "section": "Season 2",
        "label": "S02 E10 · Episode 35",
        "mediaId": "e35",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=35",
        "r2Key": "anime/attack-on-titan/e35.mp4",
        "videoPath": "/video/anime/attack-on-titan/e35",
        "downloadPath": "/download/anime/attack-on-titan/e35"
      },
      {
        "episode": 36,
        "title": "Charge",
        "animeSeason": 2,
        "seasonEpisode": 11,
        "group": "main",
        "section": "Season 2",
        "label": "S02 E11 · Episode 36",
        "mediaId": "e36",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=36",
        "r2Key": "anime/attack-on-titan/e36.mp4",
        "videoPath": "/video/anime/attack-on-titan/e36",
        "downloadPath": "/download/anime/attack-on-titan/e36"
      },
      {
        "episode": 37,
        "title": "Scream",
        "animeSeason": 2,
        "seasonEpisode": 12,
        "group": "main",
        "section": "Season 2",
        "label": "S02 E12 · Episode 37",
        "mediaId": "e37",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=37",
        "r2Key": "anime/attack-on-titan/e37.mp4",
        "videoPath": "/video/anime/attack-on-titan/e37",
        "downloadPath": "/download/anime/attack-on-titan/e37"
      },
      {
        "episode": 38,
        "title": "Smoke Signal",
        "animeSeason": 3,
        "seasonEpisode": 1,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E01 · Episode 38",
        "mediaId": "e38",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=38",
        "r2Key": "anime/attack-on-titan/e38.mp4",
        "videoPath": "/video/anime/attack-on-titan/e38",
        "downloadPath": "/download/anime/attack-on-titan/e38"
      },
      {
        "episode": 39,
        "title": "Pain",
        "animeSeason": 3,
        "seasonEpisode": 2,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E02 · Episode 39",
        "mediaId": "e39",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=39",
        "r2Key": "anime/attack-on-titan/e39.mp4",
        "videoPath": "/video/anime/attack-on-titan/e39",
        "downloadPath": "/download/anime/attack-on-titan/e39"
      },
      {
        "episode": 40,
        "title": "Old Story",
        "animeSeason": 3,
        "seasonEpisode": 3,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E03 · Episode 40",
        "mediaId": "e40",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=40",
        "r2Key": "anime/attack-on-titan/e40.mp4",
        "videoPath": "/video/anime/attack-on-titan/e40",
        "downloadPath": "/download/anime/attack-on-titan/e40"
      },
      {
        "episode": 41,
        "title": "Trust",
        "animeSeason": 3,
        "seasonEpisode": 4,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E04 · Episode 41",
        "mediaId": "e41",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=41",
        "r2Key": "anime/attack-on-titan/e41.mp4",
        "videoPath": "/video/anime/attack-on-titan/e41",
        "downloadPath": "/download/anime/attack-on-titan/e41"
      },
      {
        "episode": 42,
        "title": "Reply",
        "animeSeason": 3,
        "seasonEpisode": 5,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E05 · Episode 42",
        "mediaId": "e42",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=42",
        "r2Key": "anime/attack-on-titan/e42.mp4",
        "videoPath": "/video/anime/attack-on-titan/e42",
        "downloadPath": "/download/anime/attack-on-titan/e42"
      },
      {
        "episode": 43,
        "title": "Sin",
        "animeSeason": 3,
        "seasonEpisode": 6,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E06 · Episode 43",
        "mediaId": "e43",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=43",
        "r2Key": "anime/attack-on-titan/e43.mp4",
        "videoPath": "/video/anime/attack-on-titan/e43",
        "downloadPath": "/download/anime/attack-on-titan/e43"
      },
      {
        "episode": 44,
        "title": "Wish",
        "animeSeason": 3,
        "seasonEpisode": 7,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E07 · Episode 44",
        "mediaId": "e44",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=44",
        "r2Key": "anime/attack-on-titan/e44.mp4",
        "videoPath": "/video/anime/attack-on-titan/e44",
        "downloadPath": "/download/anime/attack-on-titan/e44"
      },
      {
        "episode": 45,
        "title": "Outside the Walls of Orvud District",
        "animeSeason": 3,
        "seasonEpisode": 8,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E08 · Episode 45",
        "mediaId": "e45",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=45",
        "r2Key": "anime/attack-on-titan/e45.mp4",
        "videoPath": "/video/anime/attack-on-titan/e45",
        "downloadPath": "/download/anime/attack-on-titan/e45"
      },
      {
        "episode": 46,
        "title": "Ruler of the Walls",
        "animeSeason": 3,
        "seasonEpisode": 9,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E09 · Episode 46",
        "mediaId": "e46",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=46",
        "r2Key": "anime/attack-on-titan/e46.mp4",
        "videoPath": "/video/anime/attack-on-titan/e46",
        "downloadPath": "/download/anime/attack-on-titan/e46"
      },
      {
        "episode": 47,
        "title": "Friends",
        "animeSeason": 3,
        "seasonEpisode": 10,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E10 · Episode 47",
        "mediaId": "e47",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=47",
        "r2Key": "anime/attack-on-titan/e47.mp4",
        "videoPath": "/video/anime/attack-on-titan/e47",
        "downloadPath": "/download/anime/attack-on-titan/e47"
      },
      {
        "episode": 48,
        "title": "Bystander",
        "animeSeason": 3,
        "seasonEpisode": 11,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E11 · Episode 48",
        "mediaId": "e48",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=48",
        "r2Key": "anime/attack-on-titan/e48.mp4",
        "videoPath": "/video/anime/attack-on-titan/e48",
        "downloadPath": "/download/anime/attack-on-titan/e48"
      },
      {
        "episode": 49,
        "title": "Night of the Battle to Retake the Wall",
        "animeSeason": 3,
        "seasonEpisode": 12,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E12 · Episode 49",
        "mediaId": "e49",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=49",
        "r2Key": "anime/attack-on-titan/e49.mp4",
        "videoPath": "/video/anime/attack-on-titan/e49",
        "downloadPath": "/download/anime/attack-on-titan/e49"
      },
      {
        "episode": 50,
        "title": "The Town Where Everything Began",
        "animeSeason": 3,
        "seasonEpisode": 13,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E13 · Episode 50",
        "mediaId": "e50",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=50",
        "r2Key": "anime/attack-on-titan/e50.mp4",
        "videoPath": "/video/anime/attack-on-titan/e50",
        "downloadPath": "/download/anime/attack-on-titan/e50"
      },
      {
        "episode": 51,
        "title": "Thunder Spears",
        "animeSeason": 3,
        "seasonEpisode": 14,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E14 · Episode 51",
        "mediaId": "e51",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=51",
        "r2Key": "anime/attack-on-titan/e51.mp4",
        "videoPath": "/video/anime/attack-on-titan/e51",
        "downloadPath": "/download/anime/attack-on-titan/e51"
      },
      {
        "episode": 52,
        "title": "Descent",
        "animeSeason": 3,
        "seasonEpisode": 15,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E15 · Episode 52",
        "mediaId": "e52",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=52",
        "r2Key": "anime/attack-on-titan/e52.mp4",
        "videoPath": "/video/anime/attack-on-titan/e52",
        "downloadPath": "/download/anime/attack-on-titan/e52"
      },
      {
        "episode": 53,
        "title": "Perfect Game",
        "animeSeason": 3,
        "seasonEpisode": 16,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E16 · Episode 53",
        "mediaId": "e53",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=53",
        "r2Key": "anime/attack-on-titan/e53.mp4",
        "videoPath": "/video/anime/attack-on-titan/e53",
        "downloadPath": "/download/anime/attack-on-titan/e53"
      },
      {
        "episode": 54,
        "title": "Hero",
        "animeSeason": 3,
        "seasonEpisode": 17,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E17 · Episode 54",
        "mediaId": "e54",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=54",
        "r2Key": "anime/attack-on-titan/e54.mp4",
        "videoPath": "/video/anime/attack-on-titan/e54",
        "downloadPath": "/download/anime/attack-on-titan/e54"
      },
      {
        "episode": 55,
        "title": "Midnight Sun",
        "animeSeason": 3,
        "seasonEpisode": 18,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E18 · Episode 55",
        "mediaId": "e55",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=55",
        "r2Key": "anime/attack-on-titan/e55.mp4",
        "videoPath": "/video/anime/attack-on-titan/e55",
        "downloadPath": "/download/anime/attack-on-titan/e55"
      },
      {
        "episode": 56,
        "title": "The Basement",
        "animeSeason": 3,
        "seasonEpisode": 19,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E19 · Episode 56",
        "mediaId": "e56",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=56",
        "r2Key": "anime/attack-on-titan/e56.mp4",
        "videoPath": "/video/anime/attack-on-titan/e56",
        "downloadPath": "/download/anime/attack-on-titan/e56"
      },
      {
        "episode": 57,
        "title": "That Day",
        "animeSeason": 3,
        "seasonEpisode": 20,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E20 · Episode 57",
        "mediaId": "e57",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=57",
        "r2Key": "anime/attack-on-titan/e57.mp4",
        "videoPath": "/video/anime/attack-on-titan/e57",
        "downloadPath": "/download/anime/attack-on-titan/e57"
      },
      {
        "episode": 58,
        "title": "Attack Titan",
        "animeSeason": 3,
        "seasonEpisode": 21,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E21 · Episode 58",
        "mediaId": "e58",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=58",
        "r2Key": "anime/attack-on-titan/e58.mp4",
        "videoPath": "/video/anime/attack-on-titan/e58",
        "downloadPath": "/download/anime/attack-on-titan/e58"
      },
      {
        "episode": 59,
        "title": "The Other Side of the Wall",
        "animeSeason": 3,
        "seasonEpisode": 22,
        "group": "main",
        "section": "Season 3",
        "label": "S03 E22 · Episode 59",
        "mediaId": "e59",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=59",
        "r2Key": "anime/attack-on-titan/e59.mp4",
        "videoPath": "/video/anime/attack-on-titan/e59",
        "downloadPath": "/download/anime/attack-on-titan/e59"
      },
      {
        "episode": 60,
        "title": "The Other Side of the Sea",
        "animeSeason": 4,
        "seasonEpisode": 1,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E01 · Episode 60",
        "mediaId": "e60",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=60",
        "r2Key": "anime/attack-on-titan/e60.mp4",
        "videoPath": "/video/anime/attack-on-titan/e60",
        "downloadPath": "/download/anime/attack-on-titan/e60"
      },
      {
        "episode": 61,
        "title": "Midnight Train",
        "animeSeason": 4,
        "seasonEpisode": 2,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E02 · Episode 61",
        "mediaId": "e61",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=61",
        "r2Key": "anime/attack-on-titan/e61.mp4",
        "videoPath": "/video/anime/attack-on-titan/e61",
        "downloadPath": "/download/anime/attack-on-titan/e61"
      },
      {
        "episode": 62,
        "title": "The Door of Hope",
        "animeSeason": 4,
        "seasonEpisode": 3,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E03 · Episode 62",
        "mediaId": "e62",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=62",
        "r2Key": "anime/attack-on-titan/e62.mp4",
        "videoPath": "/video/anime/attack-on-titan/e62",
        "downloadPath": "/download/anime/attack-on-titan/e62"
      },
      {
        "episode": 63,
        "title": "From One Hand to Another",
        "animeSeason": 4,
        "seasonEpisode": 4,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E04 · Episode 63",
        "mediaId": "e63",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=63",
        "r2Key": "anime/attack-on-titan/e63.mp4",
        "videoPath": "/video/anime/attack-on-titan/e63",
        "downloadPath": "/download/anime/attack-on-titan/e63"
      },
      {
        "episode": 64,
        "title": "Declaration of War",
        "animeSeason": 4,
        "seasonEpisode": 5,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E05 · Episode 64",
        "mediaId": "e64",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=64",
        "r2Key": "anime/attack-on-titan/e64.mp4",
        "videoPath": "/video/anime/attack-on-titan/e64",
        "downloadPath": "/download/anime/attack-on-titan/e64"
      },
      {
        "episode": 65,
        "title": "The War Hammer Titan",
        "animeSeason": 4,
        "seasonEpisode": 6,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E06 · Episode 65",
        "mediaId": "e65",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=65",
        "r2Key": "anime/attack-on-titan/e65.mp4",
        "videoPath": "/video/anime/attack-on-titan/e65",
        "downloadPath": "/download/anime/attack-on-titan/e65"
      },
      {
        "episode": 66,
        "title": "Assault",
        "animeSeason": 4,
        "seasonEpisode": 7,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E07 · Episode 66",
        "mediaId": "e66",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=66",
        "r2Key": "anime/attack-on-titan/e66.mp4",
        "videoPath": "/video/anime/attack-on-titan/e66",
        "downloadPath": "/download/anime/attack-on-titan/e66"
      },
      {
        "episode": 67,
        "title": "Assassin's Bullet",
        "animeSeason": 4,
        "seasonEpisode": 8,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E08 · Episode 67",
        "mediaId": "e67",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=67",
        "r2Key": "anime/attack-on-titan/e67.mp4",
        "videoPath": "/video/anime/attack-on-titan/e67",
        "downloadPath": "/download/anime/attack-on-titan/e67"
      },
      {
        "episode": 68,
        "title": "Brave Volunteers",
        "animeSeason": 4,
        "seasonEpisode": 9,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E09 · Episode 68",
        "mediaId": "e68",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=68",
        "r2Key": "anime/attack-on-titan/e68.mp4",
        "videoPath": "/video/anime/attack-on-titan/e68",
        "downloadPath": "/download/anime/attack-on-titan/e68"
      },
      {
        "episode": 69,
        "title": "A Sound Argument",
        "animeSeason": 4,
        "seasonEpisode": 10,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E10 · Episode 69",
        "mediaId": "e69",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=69",
        "r2Key": "anime/attack-on-titan/e69.mp4",
        "videoPath": "/video/anime/attack-on-titan/e69",
        "downloadPath": "/download/anime/attack-on-titan/e69"
      },
      {
        "episode": 70,
        "title": "Deceiver",
        "animeSeason": 4,
        "seasonEpisode": 11,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E11 · Episode 70",
        "mediaId": "e70",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=70",
        "r2Key": "anime/attack-on-titan/e70.mp4",
        "videoPath": "/video/anime/attack-on-titan/e70",
        "downloadPath": "/download/anime/attack-on-titan/e70"
      },
      {
        "episode": 71,
        "title": "Guides",
        "animeSeason": 4,
        "seasonEpisode": 12,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E12 · Episode 71",
        "mediaId": "e71",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=71",
        "r2Key": "anime/attack-on-titan/e71.mp4",
        "videoPath": "/video/anime/attack-on-titan/e71",
        "downloadPath": "/download/anime/attack-on-titan/e71"
      },
      {
        "episode": 72,
        "title": "Children of the Forest",
        "animeSeason": 4,
        "seasonEpisode": 13,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E13 · Episode 72",
        "mediaId": "e72",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=72",
        "r2Key": "anime/attack-on-titan/e72.mp4",
        "videoPath": "/video/anime/attack-on-titan/e72",
        "downloadPath": "/download/anime/attack-on-titan/e72"
      },
      {
        "episode": 73,
        "title": "Savagery",
        "animeSeason": 4,
        "seasonEpisode": 14,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E14 · Episode 73",
        "mediaId": "e73",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=73",
        "r2Key": "anime/attack-on-titan/e73.mp4",
        "videoPath": "/video/anime/attack-on-titan/e73",
        "downloadPath": "/download/anime/attack-on-titan/e73"
      },
      {
        "episode": 74,
        "title": "Sole Salvation",
        "animeSeason": 4,
        "seasonEpisode": 15,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E15 · Episode 74",
        "mediaId": "e74",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=74",
        "r2Key": "anime/attack-on-titan/e74.mp4",
        "videoPath": "/video/anime/attack-on-titan/e74",
        "downloadPath": "/download/anime/attack-on-titan/e74"
      },
      {
        "episode": 75,
        "title": "Above and Below",
        "animeSeason": 4,
        "seasonEpisode": 16,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E16 · Episode 75",
        "mediaId": "e75",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=75",
        "r2Key": "anime/attack-on-titan/e75.mp4",
        "videoPath": "/video/anime/attack-on-titan/e75",
        "downloadPath": "/download/anime/attack-on-titan/e75"
      },
      {
        "episode": 76,
        "title": "Judgment",
        "animeSeason": 4,
        "seasonEpisode": 17,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E17 · Episode 76",
        "mediaId": "e76",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=76",
        "r2Key": "anime/attack-on-titan/e76.mp4",
        "videoPath": "/video/anime/attack-on-titan/e76",
        "downloadPath": "/download/anime/attack-on-titan/e76"
      },
      {
        "episode": 77,
        "title": "Sneak Attack",
        "animeSeason": 4,
        "seasonEpisode": 18,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E18 · Episode 77",
        "mediaId": "e77",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=77",
        "r2Key": "anime/attack-on-titan/e77.mp4",
        "videoPath": "/video/anime/attack-on-titan/e77",
        "downloadPath": "/download/anime/attack-on-titan/e77"
      },
      {
        "episode": 78,
        "title": "Two Brothers",
        "animeSeason": 4,
        "seasonEpisode": 19,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E19 · Episode 78",
        "mediaId": "e78",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=78",
        "r2Key": "anime/attack-on-titan/e78.mp4",
        "videoPath": "/video/anime/attack-on-titan/e78",
        "downloadPath": "/download/anime/attack-on-titan/e78"
      },
      {
        "episode": 79,
        "title": "Memories of the Future",
        "animeSeason": 4,
        "seasonEpisode": 20,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E20 · Episode 79",
        "mediaId": "e79",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=79",
        "r2Key": "anime/attack-on-titan/e79.mp4",
        "videoPath": "/video/anime/attack-on-titan/e79",
        "downloadPath": "/download/anime/attack-on-titan/e79"
      },
      {
        "episode": 80,
        "title": "From You, 2,000 Years Ago",
        "animeSeason": 4,
        "seasonEpisode": 21,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E21 · Episode 80",
        "mediaId": "e80",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=80",
        "r2Key": "anime/attack-on-titan/e80.mp4",
        "videoPath": "/video/anime/attack-on-titan/e80",
        "downloadPath": "/download/anime/attack-on-titan/e80"
      },
      {
        "episode": 81,
        "title": "Thaw",
        "animeSeason": 4,
        "seasonEpisode": 22,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E22 · Episode 81",
        "mediaId": "e81",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=81",
        "r2Key": "anime/attack-on-titan/e81.mp4",
        "videoPath": "/video/anime/attack-on-titan/e81",
        "downloadPath": "/download/anime/attack-on-titan/e81"
      },
      {
        "episode": 82,
        "title": "Sunset",
        "animeSeason": 4,
        "seasonEpisode": 23,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E23 · Episode 82",
        "mediaId": "e82",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=82",
        "r2Key": "anime/attack-on-titan/e82.mp4",
        "videoPath": "/video/anime/attack-on-titan/e82",
        "downloadPath": "/download/anime/attack-on-titan/e82"
      },
      {
        "episode": 83,
        "title": "Pride",
        "animeSeason": 4,
        "seasonEpisode": 24,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E24 · Episode 83",
        "mediaId": "e83",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=83",
        "r2Key": "anime/attack-on-titan/e83.mp4",
        "videoPath": "/video/anime/attack-on-titan/e83",
        "downloadPath": "/download/anime/attack-on-titan/e83"
      },
      {
        "episode": 84,
        "title": "Night of the End",
        "animeSeason": 4,
        "seasonEpisode": 25,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E25 · Episode 84",
        "mediaId": "e84",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=84",
        "r2Key": "anime/attack-on-titan/e84.mp4",
        "videoPath": "/video/anime/attack-on-titan/e84",
        "downloadPath": "/download/anime/attack-on-titan/e84"
      },
      {
        "episode": 85,
        "title": "Traitor",
        "animeSeason": 4,
        "seasonEpisode": 26,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E26 · Episode 85",
        "mediaId": "e85",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=85",
        "r2Key": "anime/attack-on-titan/e85.mp4",
        "videoPath": "/video/anime/attack-on-titan/e85",
        "downloadPath": "/download/anime/attack-on-titan/e85"
      },
      {
        "episode": 86,
        "title": "Retrospective",
        "animeSeason": 4,
        "seasonEpisode": 27,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E27 · Episode 86",
        "mediaId": "e86",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=86",
        "r2Key": "anime/attack-on-titan/e86.mp4",
        "videoPath": "/video/anime/attack-on-titan/e86",
        "downloadPath": "/download/anime/attack-on-titan/e86"
      },
      {
        "episode": 87,
        "title": "The Dawn of Humanity",
        "animeSeason": 4,
        "seasonEpisode": 28,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E28 · Episode 87",
        "mediaId": "e87",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=87",
        "r2Key": "anime/attack-on-titan/e87.mp4",
        "videoPath": "/video/anime/attack-on-titan/e87",
        "downloadPath": "/download/anime/attack-on-titan/e87"
      },
      {
        "episode": 88,
        "title": "The Rumbling",
        "animeSeason": 4,
        "seasonEpisode": 29,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E29 · Episode 88",
        "mediaId": "e88",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=88",
        "r2Key": "anime/attack-on-titan/e88.mp4",
        "videoPath": "/video/anime/attack-on-titan/e88",
        "downloadPath": "/download/anime/attack-on-titan/e88"
      },
      {
        "episode": 89,
        "title": "The Wings of Freedom",
        "animeSeason": 4,
        "seasonEpisode": 30,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E30 · Episode 89",
        "mediaId": "e89",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=89",
        "r2Key": "anime/attack-on-titan/e89.mp4",
        "videoPath": "/video/anime/attack-on-titan/e89",
        "downloadPath": "/download/anime/attack-on-titan/e89"
      },
      {
        "episode": 90,
        "title": "In the Depths of Despair",
        "animeSeason": 4,
        "seasonEpisode": 31,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E31 · Episode 90",
        "mediaId": "e90",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=90",
        "r2Key": "anime/attack-on-titan/e90.mp4",
        "videoPath": "/video/anime/attack-on-titan/e90",
        "downloadPath": "/download/anime/attack-on-titan/e90"
      },
      {
        "episode": 91,
        "title": "The Battle of Heaven and Earth",
        "animeSeason": 4,
        "seasonEpisode": 32,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E32 · Episode 91",
        "mediaId": "e91",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=91",
        "r2Key": "anime/attack-on-titan/e91.mp4",
        "videoPath": "/video/anime/attack-on-titan/e91",
        "downloadPath": "/download/anime/attack-on-titan/e91"
      },
      {
        "episode": 92,
        "title": "Dedicate Your Heart",
        "animeSeason": 4,
        "seasonEpisode": 33,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E33 · Episode 92",
        "mediaId": "e92",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=92",
        "r2Key": "anime/attack-on-titan/e92.mp4",
        "videoPath": "/video/anime/attack-on-titan/e92",
        "downloadPath": "/download/anime/attack-on-titan/e92"
      },
      {
        "episode": 93,
        "title": "A Long Dream",
        "animeSeason": 4,
        "seasonEpisode": 34,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E34 · Episode 93",
        "mediaId": "e93",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=93",
        "r2Key": "anime/attack-on-titan/e93.mp4",
        "videoPath": "/video/anime/attack-on-titan/e93",
        "downloadPath": "/download/anime/attack-on-titan/e93"
      },
      {
        "episode": 94,
        "title": "Toward the Tree on That Hill",
        "animeSeason": 4,
        "seasonEpisode": 35,
        "group": "main",
        "section": "The Final Season",
        "label": "S04 E35 · Episode 94",
        "mediaId": "e94",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=94",
        "r2Key": "anime/attack-on-titan/e94.mp4",
        "videoPath": "/video/anime/attack-on-titan/e94",
        "downloadPath": "/download/anime/attack-on-titan/e94"
      },
      {
        "episode": 95,
        "title": "The Final Chapters (Part 1)",
        "group": "final-specials",
        "section": "Final Chapters · full-length specials",
        "label": "Final Chapters Special 1",
        "mediaId": "sp01",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=95",
        "r2Key": "anime/attack-on-titan/sp01.mp4",
        "videoPath": "/video/anime/attack-on-titan/sp01",
        "downloadPath": "/download/anime/attack-on-titan/sp01"
      },
      {
        "episode": 96,
        "title": "The Final Chapters (Part 2)",
        "group": "final-specials",
        "section": "Final Chapters · full-length specials",
        "label": "Final Chapters Special 2",
        "mediaId": "sp02",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=96",
        "r2Key": "anime/attack-on-titan/sp02.mp4",
        "videoPath": "/video/anime/attack-on-titan/sp02",
        "downloadPath": "/download/anime/attack-on-titan/sp02"
      },
      {
        "episode": 101,
        "title": "Ilse's Notebook: Memoirs of a Scout Regiment Member",
        "group": "oad",
        "section": "Bonus OADs",
        "label": "OAD 1",
        "mediaId": "oad01",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=101",
        "r2Key": "anime/attack-on-titan/oad01.mp4",
        "videoPath": "/video/anime/attack-on-titan/oad01",
        "downloadPath": "/download/anime/attack-on-titan/oad01"
      },
      {
        "episode": 102,
        "title": "The Sudden Visitor: The Torturous Curse of Youth",
        "group": "oad",
        "section": "Bonus OADs",
        "label": "OAD 2",
        "mediaId": "oad02",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=102",
        "r2Key": "anime/attack-on-titan/oad02.mp4",
        "videoPath": "/video/anime/attack-on-titan/oad02",
        "downloadPath": "/download/anime/attack-on-titan/oad02"
      },
      {
        "episode": 103,
        "title": "Distress",
        "group": "oad",
        "section": "Bonus OADs",
        "label": "OAD 3",
        "mediaId": "oad03",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=103",
        "r2Key": "anime/attack-on-titan/oad03.mp4",
        "videoPath": "/video/anime/attack-on-titan/oad03",
        "downloadPath": "/download/anime/attack-on-titan/oad03"
      },
      {
        "episode": 104,
        "title": "No Regrets: Part 1",
        "group": "oad",
        "section": "Bonus OADs",
        "label": "OAD 4",
        "mediaId": "oad04",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=104",
        "r2Key": "anime/attack-on-titan/oad04.mp4",
        "videoPath": "/video/anime/attack-on-titan/oad04",
        "downloadPath": "/download/anime/attack-on-titan/oad04"
      },
      {
        "episode": 105,
        "title": "No Regrets: Part 2",
        "group": "oad",
        "section": "Bonus OADs",
        "label": "OAD 5",
        "mediaId": "oad05",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=105",
        "r2Key": "anime/attack-on-titan/oad05.mp4",
        "videoPath": "/video/anime/attack-on-titan/oad05",
        "downloadPath": "/download/anime/attack-on-titan/oad05"
      },
      {
        "episode": 106,
        "title": "Lost Girls: Wall Sina, Goodbye: Part 1",
        "group": "oad",
        "section": "Bonus OADs",
        "label": "OAD 6",
        "mediaId": "oad06",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=106",
        "r2Key": "anime/attack-on-titan/oad06.mp4",
        "videoPath": "/video/anime/attack-on-titan/oad06",
        "downloadPath": "/download/anime/attack-on-titan/oad06"
      },
      {
        "episode": 107,
        "title": "Lost Girls: Wall Sina, Goodbye: Part 2",
        "group": "oad",
        "section": "Bonus OADs",
        "label": "OAD 7",
        "mediaId": "oad07",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=107",
        "r2Key": "anime/attack-on-titan/oad07.mp4",
        "videoPath": "/video/anime/attack-on-titan/oad07",
        "downloadPath": "/download/anime/attack-on-titan/oad07"
      },
      {
        "episode": 108,
        "title": "Lost Girls: Lost in the Cruel World",
        "group": "oad",
        "section": "Bonus OADs",
        "label": "OAD 8",
        "mediaId": "oad08",
        "watchUrl": "watch.html?anime=attack-on-titan&episode=108",
        "r2Key": "anime/attack-on-titan/oad08.mp4",
        "videoPath": "/video/anime/attack-on-titan/oad08",
        "downloadPath": "/download/anime/attack-on-titan/oad08"
      }
    ]
  }
];
